# Generated by Django 5.0.1 on 2024-01-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QrCoeData',
            new_name='Barcode_Data',
        ),
    ]
